### ISSUE TITLE
Method ToString() for Array and AssociativeArray don't show string elements in quotes

### ISSUE THREAD

**Issue by lvcabral** [sjbarag/brs#275] opened 2019-07-26 06:43 UTC
Roku debugger when printing the content of an array or aa, always shows string elements in quotes:

_<Component: roArray> =
[
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    "a"
    34
    1
    <Component: roArray>
]_

**Comment by lkipke** [comment] 2021-04-01 23:15
Duplicate of #416

**Closed by lkipke** 2021-04-01 23:15 UTC
Labels: bug, duplicate, e2e, good first issue, help wanted, stdlib
