### ISSUE TITLE
Supported methods are not available as field names

### ISSUE THREAD

**Issue by vbuchii** [sjbarag/brs#621] opened 2021-02-17 14:32 UTC
Let's say that we have next object:
contentNodes = {}

Supported methods are not available as fields name

? "contentNodes.items = " contentNodes.items
? "contentNodes.count = " contentNodes.count

### On Roku:
```
    contentnodes.items = invalid
    contentnodes.count = invalid
```

### On BRS:
```
   contentnodes.items = [Function items]
   contentnodes.count = [Function count]
```

So, on Roku expression: `if contentnodes.items = invalid or contentnodes.items[0] = invalid then` is valid but while running tests not.

**Comment by lkipke** [comment] 2021-04-01 23:07
Closing as a duplicate of #437

**Closed by lkipke** 2021-04-01 23:07 UTC
Labels: bug, duplicate, interpreter, stdlib
