### ISSUE TITLE
Support period before AA string accessor

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#175] opened 2019-02-25 03:16 UTC
Roku has some weird syntax where they allow using a period before accessing an associative array value. Like this code (note the `.` between `m` and `["_uuid"]`): 

```brightscript
function Main()
   m._uuid = "123"
   print m.["_uuid"]
end function
```
![image](https://user-images.githubusercontent.com/2544493/53312122-c6472a00-3881-11e9-9ba9-b65d615c4d0f.png)

This compiles and runs, so the `brs` parser should support it. From what I can tell, these two statements work the exact same way:
`print m.["_uuid"]`
`print m["_uuid"]`

**Comment by sjbarag** [comment] 2020-01-24 19:12
Duplicate of #332 , resolved by #357 !

**Closed by sjbarag** 2020-01-24 19:12 UTC
Labels: bug, parser
