### ISSUE TITLE
Support returning "invalid" from "as object" functions

### ISSUE THREAD

**Issue by underwoo16** [sjbarag/brs#385] opened 2020-03-12 20:00 UTC
Reference implementation allows `invalid` to be returned from functions that define their return type `as object`.

Consider the following example:

```brightscript
sub main()
    print "main.brs start"
    print getObjectOrInvalid(false)
    print getObjectOrInvalid(true)
    print "main.brs end"
end sub

function getObjectOrInvalid(returnInvalid as boolean) as object
    if returnInvalid then return invalid

    return { id: "an-object" }
end function
```

This chokes on the second call to `getObjectInvalid` and throws:
```
./invalid-as-object.brs(9,26-32): Attempting to return value of type Invalid, but function getObjectOrInvalid declares return value of type Object
```

**Comment by strattonbrazil** [comment] 2020-03-13 15:28
This is very similar to #384 where the stock implementation will cast based on the param type.  The solution to one will probably show the best way to solve it for the other.

**Comment by lvcabral** [comment] 2020-03-17 18:36
It's a duplicate of #313

**Closed** 2020-03-18 04:09 UTC
